{{- if .Values.installCrds -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customsecrets.configurator.gopaddle.io
  annotations:
    "helm.sh/resource-policy": keep
spec:
  group: configurator.gopaddle.io
  version: v1alpha1
  names:
    kind: CustomSecret
    plural: customsecrets
    singular: customsecret
    shortNames:
    - ccs
  scope: Namespaced
{{- end -}}
