apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customsecrets.configurator.gopaddle.io
spec:
  group: configurator.gopaddle.io
  names:
    kind: CustomSecret
    plural: customsecrets
    singular: customsecret
    shortNames:
    - ccs
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                secretName:
                  type: string
                type:
                  type: string
                data:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
                stringData:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
                secretAnnotations:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
