apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: customconfigmaps.configurator.gopaddle.io
spec:
  group: configurator.gopaddle.io
  names:
    kind: CustomConfigMap
    plural: customconfigmaps
    singular: customconfigmap
    shortNames:
    - ccm
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                configMapName:
                  type: string
                data:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
                binaryData:
                  x-kubernetes-preserve-unknown-fields: true
                  type: object
