apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurator-controller
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas  }}
  selector:
    matchLabels:
      configurator: configurator-controller
  template:
    metadata:
      labels:
        configurator: configurator-controller
        app: configurator
    spec:
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: configurator
      serviceAccountName: configurator-controller
