kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ .Release.Name }}-configurator"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "{{ .Release.Name }}-configurator"
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-controller"
  namespace: {{ .Release.Namespace }}
