apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-controller"
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicas  }}
  selector:
    matchLabels:
      configurator: configurator-controller
  template:
    metadata:
      labels:
        configurator: configurator-controller
        app: configurator
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ coalesce .Values.image.tag .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: configurator
        resources:
          {{- .Values.resources | toYaml | nindent 10 }}
      serviceAccountName: "{{ .Release.Name }}-controller"
