apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customconfigmaps.configurator.gopaddle.io
spec:
  group: configurator.gopaddle.io
  version: v1alpha1
  names:
    kind: CustomConfigMap
    plural: customconfigmaps
    singular: customconfigmap
    shortNames:
    - ccm
  scope: Namespaced
