apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
  labels:
    testsecret: emf6j
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx 
  serviceName: "nginx"
  revisionHistoryLimit: 2
  replicas: 3 
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - mountPath: /test
          name: test-secret
      volumes:
      - name: test-secret
        secret:
          secretName: testsecret-emf6j