apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
  labels:
    testsecret: shqpb
    test: o7eje
    app: nginx
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: testsecret-shqpb
        volumeMounts:
        - mountPath: /test
          name: test-secret
      volumes:
      - name: test-secret
        secret:
          secretName: test-o7eje
